name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20.0'
      - uses: actions/checkout@v2
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui -o wsl-notify-send.exe main.go
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: wsl-notify-send
          path: wsl-notify-send.exe

      # Create release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: Release v1.0.0
          draft: false
          prerelease: false
          artifacts: |
            wsl-notify-send.exe
          artifactContentType: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
