name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20.0'
      - uses: actions/checkout@v2
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui -o wsl-notify-send.exe main.go
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: wsl-notify-send.exe
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.2
          name: wsl_notify_send_0.1
          artifacts: wsl-notify-send.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload the artifacts
      #   id: create_release
      #   uses: skx/github-action-publish-binaries@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     releaseId: ${{ needs.create_release.outputs.id }}
      #     args: 'wsl-notify-send.exe'
