name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20.0'
      - uses: actions/checkout@v2
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui -o wsl-notify-send.exe main.go
