name: Build on push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Build
      run: go get github.com/go-toast/toast && go get github.com/spf13/cobra && go build -o wsl-notify-send.exe
